import type { Metadata } from "next";
import "./index.css";

export const metadata: Metadata = {
  title: "ReactArt",
  description: "Generated by create next app",
  icons: [
    {
      rel: "icon",
      url: "/logo.png",
      type: "image/png",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        {/* explicitly preloading the font stylesheet for faster loading. */}
        <link
          rel="preload"
          href="https://fonts.googleapis.com/css2?family=Audiowide&family=Sofia&display=swap"
          as="style"
        />
        {/* https://www.w3.org/TR/css-fonts-4/#font-display-desc */}
        <link
          href="https://fonts.googleapis.com/css2?family=Audiowide&family=Sofia&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        {/*className={`${geistSans.variable} ${geistMono.variable}`} */}
        {children}
      </body>
    </html>
  );
}
